### ISSUE TITLE
1.2.0 is not in maven central?

### ISSUE THREAD

**Issue by aillusions** [awslabs/amazon-dynamodb-lock-client#33]
Seems like 1.2.0 is not in maven central

**Comment by leandrodelsole** [comment]
I think the reason of this project not being released is because [AWS SDK](https://github.com/aws/aws-sdk-java) 1.2.x is not released yet as well. At the moment of writing it is 1.1.163.  
However, I agree with you it shouldn't be stated in the README the dependency is 1.2.0.
Then, we have to refer to [maven central](https://mvnrepository.com/artifact/com.amazonaws/dynamodb-lock-client) and find the last stable release is (at the moment of writing) 1.1.0.

**Comment by lalib** [comment]
I agree it should be added into maven central.

**Comment by akimkelar** [comment]
1.1.0 requires "AmazonDynamoDB" for a builder, that can not be resolved or cast from DynamoDbClient. In version 1.2.0 it´s fixed. How it could be solved? There is no working documentation for that. Is the project really dead?

**Comment by neseleznev** [comment]
We had to add FIXME in pom.xml as a temporary workaround:
```xml
        <dependency>
            <groupId>com.github.awslabs</groupId>
            <artifactId>amazon-dynamodb-lock-client</artifactId>
            <version>4b99836f7602d5e0691a5a6b27c7dba6886da901</version>
<!--FIXME folks from awslabs forgot to release version for AWS SDK 2.x, so we fetch version by commit hash -->
<!-- Latest available is 1.1.0, however master branch contains required 1.2.0 -->
<!--            <version>1.2.0</version>-->
        </dependency>
...
    <repositories>
        <repository>
            <id>jitpack.io</id>
            <url>https://jitpack.io</url>
        </repository>
    </repositories>
```

Seems like this temporary workaround will last forever

**Comment by cruizba** [comment]
It's sad to see such a good project that bad maintained. What is the problem on updating the library to 1.2.0 in maven central?

**Comment by petrac-daniel** [comment]
Is there any update on this issue?

**Comment by frotsch** [comment]
We need it too!

**Comment by biscout24** [comment]
Plus one

**Comment by madhvi08dhaundiyal** [comment]
+1

**Comment by rahil-c** [comment]
Hi all, was wondering what is the timeline for uploading the 1.2.0 jars with the java sdk v2 packages to mvn central.

**Comment by shetsa-amzn** [comment]
Newer version of Amazon DynamoDB Lock Client(1.2.0) available on Maven now

https://repo1.maven.org/maven2/com/amazonaws/dynamodb-lock-client/1.2.0/

This change includes AWS SDK upgraded to `2.20.8`
