### ISSUE TITLE
Document default permission set

### ISSUE THREAD

**Issue by sudoforge** [awslabs/amazon-dynamodb-lock-client#38]
It would be nice to document the minimum permissions needed in order to utilize this library. From what I can tell, consumers need:

- `dynamodb:DeleteItem`
- `dynamodb:DescribeTable`
- `dynamodb:GetItem`
- `dynamodb:PutItem`
- `dynamodb:Scan`
- `dynamodb:UpdateItem`

... with an optional `dynamodb:CreateTable`, if someone wanted to write their application so that it could create tables in DynamoDB (which should probably be discouraged if this library is being used for a web application, internal or not).

**Comment by seeebiii** [comment]
Just a quick addition as I was searching for that as well: `dynamodb:DescribeTable` is also optional if you don't call `AmazonDynamoDBLockClient.assertLockTableExists` or `AmazonDynamoDBLockClient.lockTableExists`.

**Comment by sudoforge** [comment]
closed in a6e9ce4863954f64bb9cc342b92243f0b33eb35e
