### ISSUE TITLE
Unable to have dynamo-db-client as a maven dependency for version 1.2.0

### ISSUE THREAD

**Issue by 5331k** [awslabs/amazon-dynamodb-lock-client#43]
I am using this dependency in my pom file, but unfortunately maven failed to read artifact however when i change version to 1.1.0 , everything works fine. :

com.amazonaws
dynamodb-lock-client
1.2.0

**Comment by 5331k** [comment]
Any comments ?, Any help will be much appreciated

**Comment by CandleCandle** [comment]
This appears to be a duplicate of #33

**Comment by shetsa-amzn** [comment]
Newer version of Amazon DynamoDB Lock Client(1.2.0) available on Maven now

https://repo1.maven.org/maven2/com/amazonaws/dynamodb-lock-client/1.2.0/

This change includes AWS SDK upgraded to `2.20.8`
