### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by ToastShaman** [awslabs/amazon-dynamodb-lock-client#47]
I wanted to ask whether this project is dead because I would need #33 to be resolved before I can use this library. If yes, are there any alternatives I can use?

**Comment by albertoandreottiATgmail** [comment]
A better question would be, "has this project ever been alive"?

**Comment by shetsa-amzn** [comment]
Newer version of Amazon DynamoDB Lock Client(1.2.0) available on Maven now

https://repo1.maven.org/maven2/com/amazonaws/dynamodb-lock-client/1.2.0/

This change includes AWS SDK upgraded to `2.20.8`
