### ISSUE TITLE
Release supported version using AWS SDK v2.

### ISSUE THREAD

**Issue by cnauroth** [awslabs/amazon-dynamodb-lock-client#48]
This pull request integrated with AWS SDK v2 on the master branch:

https://github.com/awslabs/dynamodb-lock-client/pull/19

However, it is described as "preliminary".  From what I can tell, there is not yet a formally supported release with AWS SDK v2 support.

I'd like to request completion of this feature and distribution of a new Maven release.  Right now, projects using dynamodb-lock-client are forced into a transitive dependency on AWS SDK v1, even if their codebase otherwise has migrated to AWS SDK v2.

**Comment by cnauroth** [comment]
FWIW, I built the current master branch code and linked one of my applications with it.  Everything worked fine, and all of my application's tests passed.  That's a good sign that the core functionality works, though the original MR mentions a potential feature gap around metrics.

**Comment by reibitto** [comment]
I was looking for this too. If it's still not quite production-ready, perhaps a release candidate would be an alright solution in the meantime? That would allow people to test it in real applications easier and give feedback if any bugs are found.

**Comment by tomasbrimor** [comment]
Any update on this?

**Comment by tbfky** [comment]
Any update on this?

**Comment by aleksanderEE** [comment]
@amcp any chance that will happen?

**Comment by martin-nginio** [comment]
Hi @khanshariquem  @amcp  

What does it take to finish the upgrade to AWS SDK v2 and publish it to maven.

There seems to be great interest in this project as it's a simple and reliable distributed lock. 

If you have time to review and engage then perhaps the community using the tool can help with this upgrade? 

Thanks. 

Regards,
Martin

**Comment by humanzz** [comment]
Hi team, any updates on this?

**Comment by biscout24** [comment]
Hi team, do you have any plans to release sdk v2 support?

**Comment by dmytrodanilenkov** [comment]
@artembilan I probably can finish this issue. As I understand, main thing we need to do is return metrics collector support.

**Comment by shetsa-amzn** [comment]
Newer version of Amazon DynamoDB Lock Client(1.2.0) available on Maven now

https://repo1.maven.org/maven2/com/amazonaws/dynamodb-lock-client/1.2.0/

This change includes AWS SDK upgraded to `2.20.8`

**Comment by dlabey** [comment]
Thank you!
