### ISSUE TITLE
Can we push the 1.2.0 release to the maven repo?

### ISSUE THREAD

**Issue by zhedoubushishi** [awslabs/amazon-dynamodb-lock-client#61]
I see that the master has been upgraded to 1.2.0 but haven't cut like a release for it, nor can the jars for this version be found in maven.

**Comment by vsingh-ai** [comment]
I have also been waiting for it for sometime. It would be great if it could be released.

**Comment by CandleCandle** [comment]
Looks to be a duplicate of #33

**Comment by dlabey** [comment]
Can we get a release?

**Comment by rahil-c** [comment]
Hi all, was wondering what is the timeline for uploading the 1.2.0 jars with the java sdk v2 packages to mvn central.

**Comment by shetsa-amzn** [comment]
Newer version of Amazon DynamoDB Lock Client(1.2.0) available on Maven now

https://mvnrepository.com/artifact/com.amazonaws/dynamodb-lock-client

This change includes AWS SDK upgraded to `2.20.8`
