### ISSUE TITLE
Will the latest release be pushed to Maven?

### ISSUE THREAD

**Issue by bengaudiosi-toast** [awslabs/amazon-dynamodb-lock-client#66]
I noticed the latest version is not on Maven, making it incompatible with the DynamoDB sdk v2, preventing us from upgrading.

**Comment by shetsa-amzn** [comment]
Newer version of Amazon DynamoDB Lock Client(1.2.0) available on Maven now

https://mvnrepository.com/artifact/com.amazonaws/dynamodb-lock-client

This change includes AWS SDK upgraded to `2.20.8`
