### ISSUE TITLE
Upgrade to JDK17+

### ISSUE THREAD

**Issue by chris-ryan-square** [awslabs/amazon-dynamodb-lock-client#75]
This code fails to build using JDK17.

For me, I would be ok if this was for the newer SDK version only.

**Comment by shetsa-amzn** [comment]
Newer version of Amazon DynamoDB Lock Client(1.2.0) available on Maven now

https://mvnrepository.com/artifact/com.amazonaws/dynamodb-lock-client

This change includes AWS SDK upgraded to `2.20.8`
