### ISSUE TITLE
sdk v2 port

### ISSUE THREAD

**Issue by gibffe** [awslabs/amazon-dynamodb-lock-client#9]
Any plans to port to sdk v2 ?

**Comment by PyvesB** [comment]
Thanks, looking forward to the SDK V2 support as well.

**Comment by gibffe** [comment]
Cool, we ended up implementing our custom lock inspired by this project.
Would love to switch to using the library instead.

-- gibffe

**Comment by leandrodelsole** [comment]
Any news on this?

@gibffe is your lib using sdk v2? If so, can you make it open source?

**Comment by gibffe** [comment]
I can extract what we have to a separate project in my repo. Will ping this
thread when done.

Lucas

**Comment by shetsa-amzn** [comment]
Newer version of Amazon DynamoDB Lock Client(1.2.0) available on Maven now

https://mvnrepository.com/artifact/com.amazonaws/dynamodb-lock-client

This change includes AWS SDK upgraded to `2.20.8`
